version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: lyrahgames/graphics-environment:latest
    steps:
      - checkout
      - run:
          name: build
          command: |
            mkdir code/build
            cd code/build
            cmake ..
            cmake --build .
      - persist_to_workspace:
          root: .
          paths:
            - code/build

  test:
    docker:
      - image: lyrahgames/graphics-environment:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: |
            cd code/build
            ctest --verbose